### ISSUE TITLE
Script used to generate OCR

### ISSUE THREAD

**Issue by clingerman** [danveloper/jfk-files#1]
Do you plan to share the script you used to generate the OCR data? I would be very interested in that, as it would be helpful to us in future applications!

**Comment by danveloper** [comment]
I didn't write a script, but I'll spell out what I did. You need ImageMagick and Tesseract for this to work. On a Mac, you can easily `brew install` both these things.

First, I downloaded the XLS file from the National Archive site and exported it to CSV. The first column was the name of the PDF, so I was able to use this to download all the PDFs instead of waiting for a bulk download request.

```shell
for i in $(cat ~/Downloads/jfkrelease-2017-dce65d0ec70a54d5744de17d280f3ad2.xlsx\ -\ Sheet1.csv  | cut -d',' -f1 | awk '{print tolower($0)}'); do curl -O https://www.archives.gov/files/research/jfk/releases/$i; done
```

For Tesseract OCR to work, the PDFs needed to be in PNG format, so I used ImageMagick for that conversion. Worth noting this took a long fucking time because the image density needed to be so high. I ran it through on lower densities, but I couldn't extract much valuable OCR data.

```shell
for i in $(ls *.pdf); do echo $i;  convert -colorspace GRAY -density 300 $i `echo $i | sed -e s/\.pdf/\.png/`; done
```

Finally, I used Tesseract to output the OCR to text files.

```shell
for i in $(find . -iname "*.png"); do tesseract $i stdout -l eng > `echo $i | sed -e s/\.png/\.txt/`; done
```

That's it.
